### ISSUE TITLE
Object Constructor Question

### ISSUE THREAD

**Issue by Kimberly380** [katesowles/ks_portfolio#28]
You have a super simplified object constructor in a format I haven't seen before: 

function Project (opts) {
   for(key in opts) this[key] = opts[key];
};

Where'd you learn that fancy talk?  Think I'll have to steal it (assuming I can actually understand it)!

**Comment by katesawyerdev** [comment]
Hey Kim, I believe I found it in some starter code, but here's more information about it : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in
